spring:
  application:
    name: eureka-server
server:
  port: 8100


eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.49
  instance:
    hostname: 192.168.1.194
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

